import requests, time, json, sys

TUNNEL = "http://localhost:8000"
FAILED_TOOLS = [
    ("web_search", "Use the web_search tool to search for: current time"),
    ("web_fetch", "Use the web_fetch tool to fetch content from https://httpbin.org/get"),
    ("memory_recall", "Use the memory_recall tool to recall memory with key test_diag_key"),
    ("memory_list", "Use the memory_list tool to list all saved memories"),
    ("memory_export", "Use the memory_export tool to export all memories to C:\\Users\\offic\\EAA\\diag_export.json"),
    ("hash_text", "Use the hash_text tool to hash the text hello with sha256"),
    ("csv_read", "Use the csv_read tool to read the CSV file at C:\\Users\\offic\\EAA\\test.csv"),
    ("code_lint", "Use the code_lint tool to lint the Python code: x=1;y=2;print(x+y)"),
    ("code_format", "Use the code_format tool to format the Python code: x=1;y=2;print(x+y)"),
    ("code_test", "Use the code_test tool to test the Python function: def add(a,b): return a+b"),
    ("env_set", "Use the env_set tool to set the environment variable EAA_RETEST to done"),
    ("clipboard_write", "Use the clipboard_write tool to write text retest_value to clipboard"),
    ("audio_info", "Use the audio_info tool to get info about audio file C:\\Windows\\Media\\chimes.wav"),
    ("audio_transcribe", "Use the audio_transcribe tool to transcribe audio file C:\\Windows\\Media\\chimes.wav"),
    ("video_info", "Use the video_info tool to get info about video file C:\\Users\\offic\\EAA\\test_video.mp4"),
    ("video_analyze", "Use the video_analyze tool to analyze video file C:\\Users\\offic\\EAA\\test_video.mp4"),
    ("browser_open", "Use the browser_open tool to open the URL https://example.com"),
    ("browser_screenshot", "Use the browser_screenshot tool to take a screenshot"),
    ("browser_close", "Use the browser_close tool to close the browser"),
    ("browser_click", "Use the browser_click tool to click on an element"),
    ("browser_type", "Use the browser_type tool to type text into a field"),
    ("browser_scroll", "Use the browser_scroll tool to scroll down"),
    ("browser_get_text", "Use the browser_get_text tool to get page text"),
    ("notify_send", "Use the notify_send tool to send a notification with title Retest and message retest notification"),
    ("email_send", "Use the email_send tool to send an email to test@test.com with subject Test and body test body"),
    ("sms_send", "Use the sms_send tool to send an SMS to 0000000000 with message test"),
    ("app_launch", "Use the app_launch tool to launch notepad.exe"),
    ("image_generate", "Use the image_generate tool to generate an image of a red circle"),
    ("image_convert", "Use the image_convert tool to convert an image"),
    ("image_resize", "Use the image_resize tool to resize an image"),
    ("audio_generate", "Use the audio_generate tool to generate audio"),
    ("audio_convert", "Use the audio_convert tool to convert audio"),
    ("schedule_task", "Use the schedule_list tool to list scheduled tasks"),
    ("schedule_info", "Use the schedule_list tool to list all scheduled tasks"),
    ("schedule_cancel", "Use the schedule_list tool to list all scheduled tasks"),
]
