import sys, os, json
os.chdir(r'C:\Users\offic\EAA')
sys.path.insert(0, '.')
from eaa_tool_executor import create_enhanced_registry
R, _, _ = create_enhanced_registry()
p = f = 0
E = []
def T(tool, **kw):
    global p, f
    try:
        r = R.execute(tool, **kw)
        if r.success:
            p += 1; out = str(r.output or '')[:70].replace('\n',' '); print(f'PASS {tool}: {out}')
        else:
            f += 1; e = str(r.error or '')[:100].replace('\n',' '); print(f'FAIL {tool}: {e}'); E.append((tool, e))
    except Exception as ex:
        f += 1; e = str(ex)[:100].replace('\n',' '); print(f'ERR  {tool}: {e}'); E.append((tool, e))

T('read_file', path='eaa_tool_executor.py')
T('write_file', path='_tw.txt', content='hello')
T('append_file', path='_tw.txt', content=' world')
T('list_files', path='.')
T('file_exists', path='eaa_tool_executor.py')
T('create_directory', path='_td')
T('delete_file', path='_tw.txt')
T('glob', pattern='eaa_*.py', path='.')
T('grep', pattern='def ', path='eaa_tool_executor.py')
T('shell', command='echo ok')
T('web_search', query='test')
T('web_fetch', url='https://httpbin.org/get')
T('memory_save', key='_tk', value='tv')
T('memory_recall', key='_tk')
T('memory_list')
T('memory_search', query='t')
T('memory_clear')
T('memory_stats')
T('memory_export', file_path='_tm.json')
T('memory_import', file_path='_tm.json')
T('datetime')
T('calculator', expression='22*33')
T('python', code='print(77)')
T('system_info')
T('process_list')
T('env_get', name='PATH')
T('env_set', name='_TV', value='1')
T('clipboard_read')
T('clipboard_write', text='_ct')
T('screenshot')
T('app_launch', app_name='notepad.exe')
T('process_kill', pid=999999)
T('code_run', code='print(55)', language='python')
T('code_lint', file_path='eaa_tool_executor.py', language='python')
T('code_format', file_path='eaa_tool_executor.py', language='python')
T('code_test', path='.', test_type='quick')
T('git_status', repo_path='.')
T('git_log', repo_path='.', count=3)
T('git_diff', repo_path='.')
T('git_branch', repo_path='.')
T('git_commit', repo_path='.', message='_tc')
T('pdf_info', file_path='eaa_tool_executor.py')
T('pdf_read', file_path='eaa_tool_executor.py')
T('pdf_create', file_path='_tp.pdf', content='Test page')
T('docx_read', file_path='eaa_tool_executor.py')
T('docx_create', file_path='_td2.docx', content='Test doc')
T('xlsx_read', file_path='eaa_tool_executor.py')
T('xlsx_create', file_path='_tx.xlsx', headers='A,B', rows='1,2\n3,4')
T('pptx_read', file_path='eaa_tool_executor.py')
T('pptx_create', file_path='_tp2.pptx', content='Test slide')
T('image_info', image_path='eaa_tool_executor.py')
T('image_analyze', image_path='eaa_tool_executor.py')
T('image_describe', image_path='eaa_tool_executor.py')
T('ocr_extract', image_path='eaa_tool_executor.py')
T('image_convert', image_path='eaa_tool_executor.py', output_path='_tic.png', format='png')
T('image_resize', image_path='eaa_tool_executor.py', output_path='_tir.png', width=100)
T('browser_open', url='about:blank')
T('browser_get_text')
T('browser_screenshot')
T('browser_click', selector='body')
T('browser_type', selector='body', text='test')
T('browser_scroll', direction='down')
T('browser_close')
T('notify_send', title='EAA Test', message='Testing')
T('email_send', to='test@test.com', subject='EAA Test', body='Test')
T('json_parse', data='{"a":1,"b":2}')
T('csv_read', file_path='eaa_tool_executor.py')
T('csv_write', file_path='_tc.csv', headers='X,Y', rows='1,2\n3,4')
T('database_query', db_path=':memory:', query='SELECT 1+1 AS r')
T('api_call', url='https://httpbin.org/get', method='GET')
T('hash_text', text='hello world')
T('hash_file', file_path='eaa_tool_executor.py')
T('audio_info', audio_path='eaa_tool_executor.py')
T('audio_transcribe', audio_path='eaa_tool_executor.py')
T('audio_generate', text='hello', output_path='_ta.wav')
T('audio_convert', input_path='eaa_tool_executor.py', output_path='_tac.wav')
T('video_analyze', video_path='eaa_tool_executor.py')
T('video_info', video_path='eaa_tool_executor.py')
T('schedule_list')
T('schedule_info', task_id='_nt')
T('schedule_task', name='_tsk', run_at='2099-01-01 00:00', command='echo hi')
T('schedule_cancel', task_id='_nt')
T('context_save', name='_tcx', messages='test')
T('context_load', name='_tcx')
T('context_list')
T('context_delete', name='_tcx')

print(f'\n=== RESULTS: {p} PASSED, {f} FAILED ===')
if E:
    print('FAILED:')
    for n,e in E: print(f'  {n}: {e}')
for fn in ['_tw.txt','_tp.pdf','_td2.docx','_tx.xlsx','_tp2.pptx','_tc.csv','_ta.wav','_tac.wav','_tic.png','_tir.png','_tm.json']:
    try: os.remove(fn)
    except: pass
try: os.rmdir('_td')
except: pass
print('DONE')
